---
name: Unit tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]
        django: [32, 40]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade tox

      - name: Test with tox
        env:
          TOX_ENV: ${{ format('py{0}-django{1}', matrix.python-version, matrix.django) }}
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres
        run: PYTHONPATH=. tox -e $TOX_ENV
